### PR TITLE
U14 part 3

### PR DESCRIPTION
**Pull request by Mercury13**
Going on, right now…
✅ 045 dashed line → seeds
0FB 0FC no major changes: jagged lines, wrong directions, extrema, short curves to straights etc
✅ 227 228 22E replaced weapons, technical quality
✅❔ 379 to 37B enlarged to the size of 258 (actually drew from scratch)
✅❔ 42F enlarged to the size of 258
✅ 441 442 just made, widths 1389 and 695
✅❔ 443 <s>made for test</s> probably good
✅❔ 444 to 446 just made, half width is to match 442, and half height is ½

### CODE REVIEW

**Comment by Mercury13** [comment]
@dwerning, 443 done!
Please check it for usability.

**Comment by dwerning** [comment]
@Mercury13 
I feel your test very good for 443-446. 

Moreover, the same spacing will also work for the _different_ topic of overlays (447-477).

grafik

grafik

grafik

**Comment by Mercury13** [comment]
@dwerning What about tall hash? Should its advance width be ½ of normal hash, or hash width ½? Or both, with shorter hangouts?

**Comment by dwerning** [comment]
@Mercury13
Actually, ideally the issue is more complicated.

If, for example, the half shades are going to appear in a vertical group, it may shrink a little. Ideally, the widths of the hash strokes and space between the hash strokes would _not_ shrink, only the size of the rectangle.
 
Cf. the horizontal hash in two envorinments:
grafik

grafik

However, this is probably much asked. So for a start, as long as the hieroglyph alignment controls (430-43B) are not implemented, a sign with fixed size would be very helpful.

**Comment by dwerning** [comment]
BTW: note that the overlays (447-455) are even more complicated since they adapt to the canvas of the signs. The size of it are dependent on the size of the hireoglyph. Nevertheless the width and space of the hases should not shrink. This is why overlay shading is not implemented without programming.

Cf.
grafik

**Comment by Mercury13** [comment]
@dwerning That’s why I wrote “someday”. I understand that it’s complicated, and I just don’t know how to.

**Comment by Mercury13** [comment]
@dwerning 444 to 446 made somehow, though I doubt how to make 444. Got two alternatives: as I made, and almost dots at the top and bottom, but clear diagonal.

**Comment by Mercury13** [comment]
@dwerning,
At last I made myself do something.
Enlarged cartouches to the size of 258.

**Comment by Mercury13** [comment]
@dwerning 045 now seeds

**Comment by Mercury13** [comment]
@dwerning 227 228 22E

**Comment by Mercury13** [comment]
@dwerning Are you here?

**Comment by Mercury13** [comment]
@simoncozens Merge now?

**Comment by simoncozens** [comment]
Yes, thanks again for this contribution - would like to hear feedback on 0FB/0FC and then happy to merge.

**Comment by Mercury13** [comment]
@simoncozens 0FB/FC technical changes only, no changes into general look.

**Comment by Mercury13** [comment]
@simoncozens Here’re 0FB’s differences (top layer is translucent, and bottom one is visible below)
image

**Comment by Mercury13** [comment]
@simoncozens 0FB fixed back/butt junction, I’ve just noticed: too thick line, cusp node instead of smooth

**Comment by Mercury13** [comment]
@simoncozens That’s why I called you rather that Werning — I did technical changes only to baboons.

**Comment by simoncozens** [comment]
No problem, I will build and check.

**Comment by simoncozens** [comment]
LGTM, will merge. Thank you very much again for all your effort!

**Pull request merged**
