### PR TITLE
U14 pilot PR

### PR DESCRIPTION
**Pull request by Mercury13**

### CODE REVIEW

**Comment by Mercury13** [comment]
One hiero per day — is it OK? No editable SVGs right now, but I can give them.

**Comment by Mercury13** [comment]
Working on #3!

**Comment by Mercury13** [comment]
You are free to review and accept/reject, I’ll make a new one.

**Comment by dwerning** [comment]
QA
- u1300A (man drumming with fists on his chest): fine
- u13005 (kid): fine
- u13032 (king with white crown): fine

Only
- u1302d (god): beard should not be a single long curve but straight at the beginning and only curved at the end, e.g.,
grafik
grafik
This allies to all god's beards.

**Comment by Mercury13** [comment]
Sorry, concerns on 02D, do in the evening.

**Comment by Mercury13** [comment]
@dwerning, Is old Noto’s curved beard sensible anywhere, or it should be replaced with new one everywhere?

**Comment by Mercury13** [comment]
@dwerning, 02D OK

**Comment by Mercury13** [comment]
@dwerning Maybe posture of 018 → 017, 019 → 018? Or what are relations between 017, 018 and 019?

**Comment by Mercury13** [comment]
@dwerning Stopping at 03E for now, is it OK?

**Comment by dwerning** [comment]
**Review** by (@dwerning)
- 017: should be **identical in posture to 018** except for lower end of stick (sorry that I have not seen this earlier)
- 02D: (**does not show** in my FontForge!?!)
- 033: fine now, beard correct (longish/not rounded => king's beard)
- 034: fine now
- 038: fine now, beard correct (short/edged/not rounded => noble man's beard)
- 039: fine now
- 03A: beard fine (short/pointed => foreigner's beard; forgot to mention: **headdress needs to be changed** (should not be an Egyptian god's headdress; see: https://osf.io/9haqz)
- 03B: fine now
- 03C: fine now
- 03D: fine now
- 03E: fine now
- 03F: fine now
- 040: fine now
- 04E: fine now
- 057: fine now
- 075: fine now

Thank you for your work on this!

**Comment by dwerning** [comment]
> @dwerning Maybe posture of 018 → 017, 019 → 018? Or what are relations between 017, 018 and 019? If three different → maybe no change, and U14 misfired? Segoe does three different, but difference is not so drastic. I didn’t check U5. U14 states that 017=018<019. My 1st stone: make it out of 018 by leaning more and making a new stick.

Gardiner states that 018 is "less senile" than 017. Both are old man. However, his font renders both the same, afais, except for the differend ending of the stick.
019 is not an old man, always fully straight.

**Comment by Mercury13** [comment]
What about 03A? U15’s image changed, description is “seated Syrian holding stick”.
image

**Comment by Mercury13** [comment]
@dwerning  What about 03A? U15’s image changed, description is “seated Syrian holding stick”.
image

**Comment by dwerning** [comment]
> What about 03A? U15’s image changed, description is “seated Syrian holding stick”.

The current headdress is the one of gods and females. For 03A it is supposed to be a foreigner headdress. 

It is prepared to change this shape towards
grafik
in Unicode v16.

**Comment by Mercury13** [comment]
@dwerning I’ll repeat a question: 1) could you show me 068’s hat in more detail? 2) Should I change his left foot or leave as is; Gardiner and U14 are both green.

**Comment by Mercury13** [comment]
@dwerning 1305A — also change beard?
image

**Comment by Mercury13** [comment]
@dwerning As 068 wears some big hat → leave no ear.

**Comment by Mercury13** [comment]
@dwerning 03A has new hair from scratch, does not intersect with every other's hair → right?

**Comment by Mercury13** [comment]
@dwerning 064, 069 to 06D, 06F to 071, 074 — also change beards?

**Comment by dwerning** [comment]
@Mercury13 
- 05A: same nice beard as 02D please
- 02E: same nice beard as 02D please
- 068: very nice already, an extra cavity for the ear would be nice to have 
- 03A: now beautiful
- 064: beard fine enough in this resolution, I feel (but technically shape of 02D nicer)
- 069 to 06C (Amun): yes, same beard as 02D please
- 06D (Atum): yes, same beard as 02D please
- 06F (Tatenen): yes, same beard as 02D please 
- 070-071 (Ptah): leave as it is (kings beard, sic!)

**Comment by Mercury13** [comment]
I’ve left version with ear, I’ll make.
075 already done, I just looked for gods in my Unicodia which, of course, does not have new glyphs. Checked once again: removed cap from crown, redrew stem sticking from crown, removed beard.

**Comment by Mercury13** [comment]
@dwerning Final checks before merging: 017, 02D, 02E, 05A, 068
I’ll make gods one by one, and if this PR isn’t merged then, I’ll commit all at once.

**Comment by Mercury13** [comment]
@dwerning And 075, of course.

**Comment by Mercury13** [comment]
Also done 064, 069, 06A, 06B, 06C, 06D, 06F. All people and gods OK?

**Comment by Mercury13** [comment]
@dwerning Also done 064, 069, 06A, 06B, 06C, 06D, 06F. All people and gods OK?

**Comment by Mercury13** [comment]
@dwerning 06B is mirrored 06A; 06D is mirrored 06C. Right?

**Comment by Mercury13** [comment]
@dwerning Please!

**Comment by dwerning** [comment]
- 068: ear; fine now
- 03F: beard; fine now
- 05A: beard; fine now
- 02E: beard; fine now
- 017: fine
- 02D: fine
- 075: fine
- 064: beard; fine now; ideally, *remove the tiny sun disc* in the feather crown; see cap and crown in: 
grafik

- 069: beard; fine now
- 06A: beard; yes, mirrored 069, fine now
- 06B: beard; fine now
- 06C beard; yes, mirrored 06B, fine now
- 06D: beard; fine now
- 06F: beard; fine now

**Comment by dwerning** [comment]
I wonder why some signs appear at the top of the list when I load the ufo into my FontForge:
grafik

**Comment by dwerning** [comment]
@Mercury13 Sorry, I just realize now, 033 (-- my mistake --), as well as 035-037 are supposed to have the long/curved-at-the-end god's beard. This was a little bit debatable (see https://osf.io/azmvp). But it will be changed to god's beard in v16, see https://www.unicode.org/L2/L2023/23181-n5240-hieroglyphs.pdf.
grafik

**Comment by Mercury13** [comment]
King but divine beard? Interesting. I’ll make.
King with king’s beard are other hieros that’ll come in U16?

**Comment by Mercury13** [comment]
@dwerning 
064: redrew Min’s feathered crown from scratch without extra details; check whether OK
033: replaced straight king’s beard with curved god’s one
035 036 037: replaced straight king’s beard with curved god’s one, reversed curve directions so outer is CW
027: removed self-intersections, reversed curve direction so outer is CW (redrew nothing)

As font builder does big job of fixing directions, I didn’t fix for myself unless actually touched.

Do 036 and 075 portray the same crown? Whose image is better? Maybe I’ll replace them all with the best one?

**Comment by Mercury13** [comment]
@dwerning  What to do with 076, 17D?

**Comment by dwerning** [comment]
> King but divine beard? Interesting. I’ll make. King with king’s beard are other hieros that’ll come in U16?

The tricky thing is that pharaoh is king and god at the same time. The rules of interplay with specific crowns is partly unclear (at least to me). In _Thot Sign List_ https://thotsignlist.org/mysign?id=714 tthere ar not clear examples for 035 with king's beard, but only for god's beard. For 033 both shapes are testified: https://thotsignlist.org/mysign?id=679. Consequently, 035 in Gardiner/Unicode v.5.2 and again in v16 had/will have the god's beard with 035-037 and -- to be consistent with the parallel 035-037 -- also 033.

**Comment by dwerning** [comment]
- 064 (Min-Amun): very nice
- 033, 035-037: beards now in line with v5.2 and v16[proposal]

- crown in 035-037 vs. 075: yes, same crown, shape at the very top in 035-037 is better; caveat: 075 is the female god/goddess Neith; please, keep the fact/difference that there is no cloth hanging from the crown in 075 (might be relevant) 
- 076, ideally beard filled with black, little smaller altogether: 
grafik
====>
grafik
- 17D, ideally beard shorter:
grafik
=====>
grafik

**Comment by dwerning** [comment]
> ...  17D short beard

BTW: this was also a very tricky issue. Attestations often seem to have the god's beard (but not always?), cf. https://thotsignlist.org/mysign?id=3587 and https://thotsignlist.org/mysign?id=3588 (all not very clear). However, Gardiner and v9-15 all have it short (men's beard?) (v5.2 had no beard mistakenly). So the Unicode discussion group decided to stick to that shape og Gardiner/v9-15 for the time being.

**Comment by Mercury13** [comment]
@dwerning
075 = 038 − beard − cloak
076 changed beard
17D shorter beard, removed curves from rectilinear segments, fixed direction

**Comment by dwerning** [comment]
- 075: fine now (top of crown now better)
- 076: much nicer now
- 17D: clearer now

**Comment by Mercury13** [comment]
@dwerning Can merge now 34 hieros: crowns, beards?

**Comment by Mercury13** [comment]
@simoncozens Merge now?

**Comment by Mercury13** [comment]
Final check (first date when committed, then when checked)
--- 00 ---
00A Oct 9-10 OK
015 (erroneously referred as 005) Oct 09-10 OK
017 Oct 13-16 OK
02D Oct 13-16 OK
02E Oct 14-16 OK
--- 05 ---
032 Oct 9-10 OK
033 Oct 16-17 OK
034 Oct 10-13 OK
035 036 Oct 16-17 OK
--- 10 ---
037 Oct 16-17 OK
038 039 03A 03B Oct 10-13 OK
--- 15 ---
03C 03D 03E Oct 10-13 OK
03F Oct 12-13/16 OK
040 Oct 12-13 OK
--- 20 ---
04E Oct 12-13 OK
057 Oct 13 (I fell very tired on 12th, then woke up at night and worked a bit) OK
05A Oct 14-16 OK
064 Oct 16-17 OK
068 Oct 14-16 OK
--- 25 ---
069 06A 06B 06C 06D Oct 15-16 OK
--- 30 ---
06F Oct 15-16 OK
075 076 17D Oct 18 (worked at night though do not remember 😲) OK
--- Total 34

**Pull request merged**
