### PR TITLE
U14 cows etc

### PR DESCRIPTION
**Pull request by Mercury13**
@dwerning Test it…

Today: 0D2 curved horns
0D5 a bit longer neck, shorter crown, hung ankh, added a few extrema, removed points sitting nearby, little-meaning curves to straights

### CODE REVIEW

**Comment by Mercury13** [comment]
@dwerning **0FD** copied from 0D2, but 0FD’s eye, other horns, other belly (wanted exaggerated udder but stopped on 0D6-like).
All descriptions say it’s a bull. Are you sure that it’s a female cow now?

**Comment by Mercury13** [comment]
@dwerning 0FE: changed horns, increased both hangouts

**Comment by Mercury13** [comment]
@simoncozens, while our reviewer is out here, I want to ask you a small question: how will you implement hatches for damaged hieroglyphs? Draw more than 10 sets of hatches for different widths?
(This isn’t needed for my Unicodia, it heavily relies on various fix-ups, but working font is always cool.)

**Comment by dwerning** [comment]
@Mercury13 
- 0d2, 0fd, 0fe: much better; however, _ideally_, have the hornes even more curved to the outside as in 10b.
- 0fd: I would mind having a longer udder hanging a litte further down -- just to have this more clear.
- 05d: fine now.

**Comment by dwerning** [comment]
> @simoncozens, while our reviewer is out here, I want to ask you a small question: how are you going to implement hatches for damaged hieroglyphs? Draw more than 10 sets of hatches for different widths? ...

I don't know about the technicalities. However @xadxura does. 

Just one comment: you have to differentiate between the atomic hashing chars and the hashing overlay controls. The former is just normal hieroglyphic chars (U+13443-6), the latter is more difficult to implement (since overlays; U+13447-55).

Having at least the 'normal' chars
- U+13441/2 (2D blanks)
- U+13443/4 (2D atomic shading signs)

in Noto would be great (https://www.unicode.org/L2/L2021/21248-egyptian-controls.pdf).

**Comment by Mercury13** [comment]
@dwerning,
Nice to see you again!
So make horns more curved, okay.
Blanks are blanks, I understand. Shading signs are slanted hatches, aren’t they?
And is there a difference between fully-lost hieroglyph and severely damaged?
image

**Comment by dwerning** [comment]
> Shading signs are slanted hatches, aren’t they? 

yes, 45° like in 
grafik

The size of the blanks are as follows:
- 13441: same size as 13443, but completely blank of course
- 13442:  same size as 13444 (i.e. a quarter of a quadrat), but completely blank of course.

Cf. the grey areas is -- but again, not grey but just empty/blank:
grafik



> And is there a difference between fully-lost hieroglyph and severely damaged?

Yes, the atomic hashings above makr areas of complete destruction. Damaged hieroglyphs are marked by hashing overlay, i.e., the more complicated control chars above (U+13447-...).

**Comment by Mercury13** [comment]
@dwerning What to do with udder?

**Comment by dwerning** [comment]
> @dwerning What to do with udder?

I suggest
grafik
====>
grafik

**Comment by Mercury13** [comment]
But you HAVE exaggerated the udder.

**Comment by Mercury13** [comment]
@dwerning Made just 0D2, is OK?

**Comment by dwerning** [comment]
> But you HAVE exaggerated the udder.

Excuse me, I meant to say "I would NOT mind having a longer udder..."

**Comment by Mercury13** [comment]
@dwerning Is 0D2 OK? If OK, I’ll quickly fix the rest.

**Comment by dwerning** [comment]
> @dwerning Is 0D2 OK? If OK, I’ll quickly fix the rest.

Yes, great.

**Comment by Mercury13** [comment]
@dwerning 
Sorry for being away, I was a bit sick.
0FD changed horns, enlarged udder just a bit (four nipples are too many for this detail level), reimported form scratch
0FE changed horns, reimported from scratch
108 changed horns, changed width. Identified stroke 18u rather than 19, let it be
0FB Is this baboon OK?

**Comment by Mercury13** [comment]
@dwerning We left for a while. I was a bit sick, take at least 163.
Changes posture, grafted 164’s head feathers.

**Comment by Mercury13** [comment]
@dwerning Also 25F, inanimate objects start.

**Comment by Mercury13** [comment]
@dwerning Cannot fall asleep, simple inanimate hieros start. Also 267 and 26A.

**Comment by Mercury13** [comment]
@dwerning Accidentally noticed 2B1 — should I remake it like 2B4?

**Comment by Mercury13** [comment]
@dwerning 267 removed prongs, narrower glyph.
26A four rightmost snakes now point to the right. Moved 3 leftmost snakes 4 units to the left, and 4 rightmost 4 units to the right.

**Comment by Mercury13** [comment]
@dwerning 29E: is it good?

**Comment by Mercury13** [comment]
@dwerning 29F thing on the stern

**Comment by Mercury13** [comment]
@dwerning 2B4 rectangular things — right?

**Comment by dwerning** [comment]
- 0FD: nice.
- 0FE: nice.
- 108: ok, I guess (Gardiner was not sure which animal this is and says it substitutes for the older form 109 in the New Kingdom, which looks more like a bubalis, cf. 103; however, also Gardiner has the a shape which looks like a cow; so, best we can decide now).
- 0FB: fine, now clealy a barboon. Use **for 0FC too, plesae**.
- 163: nice.
- 25F: fine now.
- 267: fine now.
- 26A: fine now.
- 2B1/2B4: please leave both as they are (these are the shape as defined in the upcoming version; 2B4 is dubious, but that's the way it is).
- 297: nice.
- 29E: please have **both ends of the ship exactly like in 29F**,i.e. remove the elaborate ending on the one side: 29E is a mirrored version of 29F but with additional rudder.

Thank you, again, for your work on this.

**Comment by Mercury13** [comment]
@dwerning
2B4: revert?
29F: OK?
29E: turn papyrus to simpler stern?

**Comment by Mercury13** [comment]
@dwerning
Well, baboon has a nice “coat”, and IDK how ho convey it. I’ll try.
I’ll greatly reduce tail loop.
2B4 — I turned round breads to rectangular receptacles, leave them?

**Comment by Mercury13** [comment]
@dwerning
0FB smaller tail loop, made coat
29E 29F: simpler and exactly identical stern figure. To make 29E, I flipped 29F and grafted existing rudder oar
2B4: did nothing. See a shot from FontForge → considering OK (I use FontForge too)

Have a hard day tomorrow → go to bed

**Comment by Mercury13** [comment]
@dwerning
2C1 remade top of spear from scratch

**Comment by Mercury13** [comment]
@dwerning 379 Is position normal?

**Comment by Mercury13** [comment]
@dwerning
3F3 narrower
417 rectangular
420 removed line
42B filled semicircle
The ball is on your side now; when you confirm baboon and turned U, I’ll remake the rest

**Comment by Mercury13** [comment]
@dwerning Are you alive?

**Comment by dwerning** [comment]
Having come back from a field trip to Egypt, here is my review:

- 0FC: ***please insert same barboon as in 0FB***
- 29E, 29F: as requested; however, ***I am unsure about the papyrus stern***; Gardiner is not very clear in this respect; could you please add a smallish papyrus to the longer stern in both glyphs, i.e. to the right stern in 29E and to the left stern in 29F for now; ***I need to recheck with colleagues about the stern and the orientation of 29F: there is some confusion about it***
- 2B4: as supposed to be
- 0FB: as requested
- 2C1: nice
- 31F: ***could you move both strokes at the bottom a little more to the bottom*** (more like Gardiner had it)
- 379: fine
- 37B: ***supposed to be mirrored form of now new 379***
- 37A: ***supposed to have same height as 379/B*** (other that 378, which is fine!)
- 3F3: as requested
- 417: as requested
- 420: correct now
- 42B: as requested

**Comment by Mercury13** [comment]
@dwerning Field trip to Egypt? Was it dangerous, Egypt hasn’t always been really safe outside tourist sites, and nearby war could change something.

**Comment by dwerning** [comment]
As to the shapes of the sacred ship of Ra (29E, 29F)
- a perfect shape for the bow/rear would be similar to the shape of U+13333/4
grafik
- a perfect shape for the stern/front would be an ***un***curved, rather vertical shape.
Cf. 
https://www.alamy.com/drawing-on-stone-of-the-pharaoh-sailing-on-his-ship-made-in-black-ink-with-red-hieroglyphs-image335881066.html?imageid=31A5878E-C944-42DF-A6C9-A5D44BA387C2&p=255142&pn=1&searchId=6a05fe88b4b84b331cb47a5a969cdef6&searchtype=9
https://www.alamy.com/khufu-cheops-ship-intact-full-size-vessel-type-known-as-a-solar-barge-a-ritual-vessel-to-carry-the-resurrected-king-with-the-sun-god-ra-across-the-heavens-4th-dynasty-old-kingdom-giza-pyramid-complex-c-2500-bc-giza-solar-boat-museum-egypt-image343653965.html?imageid=A18676F9-D12B-4D28-B57E-5B27E90C0609&p=83158&pn=1&searchId=fc52f017b49a41529e897350618adee3&searchtype=0
https://www.alamy.com/stock-photo-he-three-boats-top-two-are-funeral-boats-bottom-is-boat-of-ra-pictured-31008558.html?imageid=306D21B3-45D3-4F08-A41D-40DEFBA15750&p=32409&pn=1&searchId=fc52f017b49a41529e897350618adee3&searchtype=0

Cf. Sign TSL_1_5011 <http://thotsignlist.org/mysign?id=5011>, in: Thot Sign List, ed. by Université de Liège and BBAW, Berlin; notably
P30-PPU-plate25-col26
P30-PDM-SSotGN-plate1-col1-2
P3-SPT1-W366c-page191-PPU-plate24-25-col25
P30-PNu-sheet27-spell101-line3-col23fromright

So
grafik

BTW: against the photo evidence abobe, please leave the seat as it is. The shape of the seat as evidenced in the photos will be added as U+1402B with the next addition of glyphs. The shapes of ships in hieroglyphs is admittedly still very confusing, badly researched.

**Comment by Mercury13** [comment]
I’ve seen a simple dome-shaped cockpit somewhere, so I didn’t even think to change it.
I’ll try tonight.

**Comment by Mercury13** [comment]
@dwerning Is the chair in place of cockpit King’s or god’s throne?

**Comment by Mercury13** [comment]
@dwerning 29E 9F redrew both bow and stern figures, go to bed. Thank you.

**Comment by dwerning** [comment]
> Is the chair in place of cockpit King’s or god’s throne?

In Gardiner/Unicode v5.2 it seems to be a shrine like 𓉬. 
296540124-00ea6d5b-af95-4caa-a8b0-621830486b54

Unfortunately, Hieroglyphica/Unicode v9ff shapes have the shrine symmetric (see above).

However, the evidence that Thot Sign List has on the divine ship is mostly with what I understand as a seat or throne with a shape similar to 𓊩. 
296538560-e5d7fdb2-91e1-4789-b6d1-9d2971d2b00f
This shape will be added wit Unicode v16 (codepoint not fixed yet):
grafik

Ideally, **for now,** you would make the shrine line Gardiner had it, i.e., ***non-***symmetric, the higher part near the front/stern.

**Comment by Mercury13** [comment]
@dwerning Excuse me, stern is rear. Higher part near the front, I presume?

**Comment by Mercury13** [comment]
@dwerning Excuse me, bow is front, and stern is rear. I checked dictionary once again. Higher part near the bow/front, I presume?

**Comment by Mercury13** [comment]
I thought it’s a cockpit. And there’s a shrine inside that cockpit? :)

**Comment by dwerning** [comment]
> I thought it’s a cockpit. And there’s a shrine inside that cockpit? :)

In the night, the sun god is in a shrine-shaped "cockpit", see https://en.wikipedia.org/wiki/Solar_barque#/media/File:Book_of_Gates_Barque_of_Ra_cropped.jpg. I figure that this is what Gardiner aimed at in his shape. However, I do not have or remember an image of the sun boat at daytime with any kind of seat/shrine/or else.

**Comment by Mercury13** [comment]
@dwerning
29E 9F redrew cockpits, reimported from scratch
379…37B redrew cartouches from scratch, maintaining dimensions approved by you
42F new glyph
Need just 0FC ape, but that’s lots of work

**Comment by Mercury13** [comment]
@dwerning 0FC grafted new baboon

**Comment by Mercury13** [comment]
@dwerning 31F moved to bottom via FontForge, found suboptimal node

**Comment by Mercury13** [comment]
Sorry for force-push, related to my job and your CLA.

**Comment by Mercury13** [comment]
@dwerning 37B Funky hall, again SVG. Reexporting!
I just remembered, my Unicodia displays them in some manner.

**Comment by Mercury13** [comment]
@simoncozens I made a mistake and pushed SVG instead of GLIF. IDK whether we need to re-check it (dimensions are surely OK), checking the rest. 27 files changed.
-- 00 --
contents.plist: new glyph, please check for yourself
0D2: upd Nov 7, chk Nov 8
0D5: upd Oct 29, chk Nov 7 (shown as 05D)
0FB: upd Dec 7, chk Jan 14
0FC: upd Jan 23, chk Jan 23 (worked in the night)
-- 05 --
0FD: upd Nov 14, chk Dec 2
0FE: upd Nov 14, chk Dec 2
108: upd Nov 14, chk Dec 2
163: upd Nov 29, chk Dec 2
25F: upd Nov 29, chk Dec 2
-- 10 --
267: upd Nov 29, chk Dec 2
26A: upd Nov 29, chk Dec 2
297: upd Nov 29, chk Dec 2
29E: upd Jan 22, chk Jan 23
29F: same
-- 15 --
2B4: upd Dec 1, finally confirmed Jan 14
2C1: upd Dec 13, chk Jan 14
31F: upd Jan 23, chk Jan 23 (worked in the night)
379: same
37A: same
-- 20 --
37B: upd Jan 23, still unchecked (though probably OK, it was a batch of cartouches)
3F3: upd Dec 15, chk Jan 14
417: same
420: same
42B: same
-- 25 --
42F: upd Jan 23, chk Jan 23 (worked in the night)
lib.plist: new glyph, please check for yourself

**Comment by Mercury13** [comment]
@dwerning About “normal” shadings — I’ll better collect stats and take the most frequent.

**Comment by dwerning** [comment]
> 37B Funky hall, again SVG. Reexporting! I just remembered, my Unicodia displays them in some manner.

Confirming: now its there.

**Comment by dwerning** [comment]
> About “normal” shadings — I’ll better collect stats and take the most frequent.

Note that the size/aspect ratio is fixed.
grafik

We already have stats about sign sizes. However, these are not informative since the atomic shading chars mean destroyed _surface_ rather than destroyed _sign_. For example, the small
U+133E4 EGYPTIAN HIEROGLYPH Z001 ( 𓏤 ) normally occupies a width of 50%
grafik
or 30%, only exceptionally less.

**Comment by Mercury13** [comment]
@simoncozens Everything is checked, merge now?

**Comment by Mercury13** [comment]
@dwerning Merge now?

**Comment by dwerning** [comment]
Go ahead...

**Comment by Mercury13** [comment]
@simoncozens How shall we merge?

**Comment by simoncozens** [comment]
This is amazing work, thank you both very, very much!

**Pull request merged**
